version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: ${ZK_HOST}
    ports:
      - "${ZK_PORT}:${ZK_PORT}"
    networks:
      - kafka-network
  kafka-server:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: ${ZK_HOST}:${ZK_PORT}
      KAFKA_LISTENERS: 'SSL://${BROKER_HOST}:${BROKER_PORT}'
      KAFKA_ADVERTISED_HOST_NAME: 'SSL://${BROKER_HOST}:${BROKER_PORT}'
      KAFKA_ADVERTISED_LISTENERS: 'SSL://${BROKER_HOST}:${BROKER_PORT}'
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ${keypss}
      KAFKA_SSL_KEY_CREDENTIALS: ${keypss}
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ${keypss}
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SECURITY_PROTOCOL: SSL
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
    - ./secrets:/etc/kafka/secrets
    depends_on:
      - ${ZK_HOST}
    networks:
      - kafka-network
networks:
  kafka-network:
    driver: bridge